/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'chella': ['ChellaType', 'sans-serif'],
        'montserrat': ['Montserrat', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        'bg-color': 'var(--bg-color)', 
        'navbar-bg': 'var(--navbar-bg-color)',
        'footer-bg': 'var(--footer-bg-color)',
        'card-bg': 'var(--card-bg-color)',
        'card-hover-bg': 'var(--card-hover-bg-color)',
        'default-text': 'var(--default-text-color)',
        'card-text': 'var(--card-text-color)',
        'subheadline-text': 'var(--subheadline-text-color)',
        'active-link': 'var(--active-link-color)',
        'card-title': 'var(--card-title-color)',
        'logo-text': 'var(--logo-text-color)',
        'nav-links-text': 'var(--nav-links-text-color)',
        'hover-link': 'var(--hover-link-color)',
        'primary-button': 'var(--primary-button-color)',
        'primary-button-hover': 'var(--primary-button-hover-color)',
        'secondary-button': 'var(--secondary-button-color)',
        'secondary-button-hover': 'var(--secondary-button-hover-color)',
        'card-date': 'var(--card-date-color)', 
        'card-location': 'var(--card-location-color)', 
        'card-category': 'var(--card-category-color)',
        'select-control-bg': 'var(--select-control-bg)',
        'select-control-border': 'var(--select-control-border)',
        'select-menu-bg': 'var(--select-menu-bg)',
        'select-single-value': 'var(--select-single-value)',
        'select-disabled-option': 'var(--select-disabled-option)',
        'select-selected-option': 'var(--select-selected-option)',
        'select-focused-option': 'var(--select-focused-option)',
        'select-option': 'var(--select-option)',
        'select-selected-option-bg': 'var(--select-selected-option-bg)',
        'select-focused-option-bg': 'var(--select-focused-option-bg)',
        'select-option-bg-light': 'var(--select-option-bg-light)',
        'select-option-bg': 'var(--select-option-bg)',
        'select-input': 'var(--select-input)',
        'select-placeholder': 'var(--select-placeholder)',
      },
    },
  },
  plugins: [],
};
